create table pick_n_pay (prod_id bigint not null, price double precision not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table product_sequence (next_val bigint) engine=InnoDB;
insert into product_sequence values ( 1 );
create table products (prod_id bigint not null, prod_volume double precision not null, prod_volume_unit varchar(2), title varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table shoprite (prod_id bigint not null, price double precision not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table woolworths (prod_id bigint not null, price double precision not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
alter table pick_n_pay add constraint FKrgqni4mpn3ptp0p3hn26cp25o foreign key (prod_id) references products (prod_id);
alter table shoprite add constraint FKf97888xabkcv7xf0epdgbkevv foreign key (prod_id) references products (prod_id);
alter table woolworths add constraint FKdvr8j4rts1th8qi7g80ekw9g8 foreign key (prod_id) references products (prod_id);
create table pick_n_pay (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table product_sequence (next_val bigint) engine=InnoDB;
insert into product_sequence values ( 1 );
create table products (prod_id bigint not null, prod_volume double precision not null, prod_volume_unit varchar(2), title varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table shoprite (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table woolworths (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
alter table pick_n_pay add constraint FKrgqni4mpn3ptp0p3hn26cp25o foreign key (prod_id) references products (prod_id);
alter table shoprite add constraint FKf97888xabkcv7xf0epdgbkevv foreign key (prod_id) references products (prod_id);
alter table woolworths add constraint FKdvr8j4rts1th8qi7g80ekw9g8 foreign key (prod_id) references products (prod_id);
create table pick_n_pay (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table product_sequence (next_val bigint) engine=InnoDB;
insert into product_sequence values ( 1 );
create table products (prod_id bigint not null, prod_volume double precision not null, prod_volume_unit varchar(2), title varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table shoprite (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table woolworths (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
alter table pick_n_pay add constraint FKrgqni4mpn3ptp0p3hn26cp25o foreign key (prod_id) references products (prod_id);
alter table shoprite add constraint FKf97888xabkcv7xf0epdgbkevv foreign key (prod_id) references products (prod_id);
alter table woolworths add constraint FKdvr8j4rts1th8qi7g80ekw9g8 foreign key (prod_id) references products (prod_id);
create table pick_n_pay (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table product_sequence (next_val bigint) engine=InnoDB;
insert into product_sequence values ( 1 );
create table products (prod_id bigint not null, prod_volume double precision not null, prod_volume_unit varchar(2), title varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table shoprite (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table woolworths (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
alter table pick_n_pay add constraint FKrgqni4mpn3ptp0p3hn26cp25o foreign key (prod_id) references products (prod_id);
alter table shoprite add constraint FKf97888xabkcv7xf0epdgbkevv foreign key (prod_id) references products (prod_id);
alter table woolworths add constraint FKdvr8j4rts1th8qi7g80ekw9g8 foreign key (prod_id) references products (prod_id);
create table pick_n_pay (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table product_sequence (next_val bigint) engine=InnoDB;
insert into product_sequence values ( 1 );
create table products (prod_id bigint not null, prod_volume double precision not null, prod_volume_unit varchar(2), title varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table shoprite (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
create table woolworths (prod_id bigint not null, price double precision not null, title varchar(255) not null, url varchar(255) not null, primary key (prod_id)) engine=InnoDB;
alter table pick_n_pay add constraint FKrgqni4mpn3ptp0p3hn26cp25o foreign key (prod_id) references products (prod_id);
alter table shoprite add constraint FKf97888xabkcv7xf0epdgbkevv foreign key (prod_id) references products (prod_id);
alter table woolworths add constraint FKdvr8j4rts1th8qi7g80ekw9g8 foreign key (prod_id) references products (prod_id);
